### ISSUE TITLE
Atualize README.md

### ISSUE THREAD

**Issue by kyriosdata** [MSSDavid/integracao2017#1]
Acrescente o nome de todos os integrantes do grupo logo no início.

**Comment by MSSDavid** [comment]
Feito;

**Comment by MSSDavid** [comment]
Não entendi como isso funciona. Deixar ele "closed" é pra dizer que eu resolvi?

**Comment by kyriosdata** [comment]
Exatamente @MSSDavid , você deve resolver e fechar.
